name: Measurement Tools
version: 1.2
description: The plugin helps you to find the center of an area.
author: Raith Thomas
webseite: http://www.rcraft.at

main: at.rcraft.measurementtools.MeasurementTools

commands:
    center:
        description: 'Determines the center of an area'
        usage: 'Usage: /center'
    mm:
        description: 'Measurement Tools Info'
        usage: 'Usage: /mm'
    length: 
        description: 'Get the length of the area'
        usage: 'Usage: /length <axis>'